### ISSUE TITLE
Discrepancy between Gas Station Mainnet/Testnet v2 Responses

### ISSUE THREAD

**Issue by samuelexferri** [maticnetwork/maticgasstation#35]
Hi,

I've observed that the two endpoints, v2 mainnet and testnet, return different responses:

For https://gasstation.polygon.technology/v2:
```
{
  "safeLow": {
    "maxPriorityFee": 30,
    "maxFee": 238.270559342
  },
  "standard": {
    "maxPriorityFee": 30.063437836,
    "maxFee": 238.333997178
  },
  "fast": {
    "maxPriorityFee": 45.219617058,
    "maxFee": 253.4901764
  },
  "estimatedBaseFee": 208.270559342,
  "blockTime": 2,
  "blockNumber": 51623669
}
```

And for https://gasstation-testnet.polygon.technology/v2:
```
{
  "success": true,
  "data": {
    "safeLow": {
      "maxPriorityFee": 30,
      "maxFee": 30.000000016
    },
    "standard": {
      "maxPriorityFee": 30,
      "maxFee": 30.000000016
    },
    "fast": {
      "maxPriorityFee": 30,
      "maxFee": 30.000000016
    },
    "estimatedBaseFee": 1.6e-8,
    "blockTime": 2,
    "blockNumber": 44074404
  }
}
```

I've noticed that the testnet response has encapsulated all values within a "data" object. This change appears recent, and it might have affected various libraries, such as ethers, that rely on this external centralized gas estimation (probably a plugin).

It seems that only the testnet endpoint response structure has been altered, now encapsulating the gas estimation values within a "data" object. The production endpoint remains unchanged.

To ensure consistency and prevent disruptions in services relying on this gas estimation, it would be beneficial to align the response structures of both mainnet and testnet endpoints. Also, updating the README.md file to reflect these changes after thorough checks would be advisable.

Additional error using ethers v6.9.0 with a QuickNode RPC Testnet:
```
Error: error encountered with polygon gas station ("https://gasstation-testnet.polygon.technology/v2") (request={  }, response={  }, error={  }, code=SERVER_ERROR, version=6.9.0)
    at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
    at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
    at FetchUrlFeeDataNetworkPlugin.<anonymous> (/app/node_modules/ethers/lib.commonjs/providers/network.js:290:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async JsonRpcProvider.getFeeData (/app/node_modules/ethers/lib.commonjs/providers/abstract-provider.js:619:29)
    at async Wallet.populateTransaction (/app/node_modules/ethers/lib.commonjs/providers/abstract-signer.js:109:29)
    at async Wallet.sendTransaction (/app/node_modules/ethers/lib.commonjs/providers/abstract-signer.js:182:21)
    at async send (/app/node_modules/ethers/lib.commonjs/contract/contract.js:228:20)
    at async Proxy.buySharesWithExternalPayment (/app/node_modules/ethers/lib.commonjs/contract/contract.js:261:16)
    at async exports.executebuySharesWithExternalPayment (/app/controllers/v1/item.controller.js:650:18) {
  code: 'SERVER_ERROR',
  request: FetchRequest {},
  response: FetchResponse {},
  error: TypeError: Cannot read properties of undefined (reading 'maxFee')
      at FetchUrlFeeDataNetworkPlugin.<anonymous> (/app/node_modules/ethers/lib.commonjs/providers/network.js:284:50)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async JsonRpcProvider.getFeeData (/app/node_modules/ethers/lib.commonjs/providers/abstract-provider.js:619:29)
      at async Wallet.populateTransaction (/app/node_modules/ethers/lib.commonjs/providers/abstract-signer.js:109:29)
      at async Wallet.sendTransaction (/app/node_modules/ethers/lib.commonjs/providers/abstract-signer.js:182:21)
      at async send (/app/node_modules/ethers/lib.commonjs/contract/contract.js:228:20)
      at async Proxy.buySharesWithExternalPayment (/app/node_modules/ethers/lib.commonjs/contract/contract.js:261:16)
      at async exports.executebuySharesWithExternalPayment (/app/controllers/v1/item.controller.js:650:18),
  shortMessage: 'error encountered with polygon gas station ("https://gasstation-testnet.polygon.technology/v2")'
}
```

**Comment by samuelexferri** [comment]
Probably related to ethers using this plugin?
```
    registerEth("matic-mumbai", 80001, {
        altNames: [ "maticMumbai", "maticmum" ],  // @TODO: Future remove these alts
        plugins: [
            getGasStationPlugin("https:/\/gasstation-testnet.polygon.technology/v2")
        ]
    });
```

https://github.com/ethers-io/ethers.js/blob/main/src.ts/providers/network.ts

**Comment by samuelexferri** [comment]
@nitinmittal23

**Comment by nitinmittal23** [comment]
This has been fixed
